### ISSUE TITLE
[Feature Request] Add prefix names for imported motions

### ISSUE THREAD

**Issue by xDShot** [PavelBlend/blender-xray#210]
My current project involves importing several animated objects (weapon hud objects and animations for ex.) that have the same actions names into one scene. This results in names collision and bone keyframes override. Would be glad if there's import option to add own prefix name (specify own or put importing file name), or give me directions how can I implement that.

**Comment by igelbox** [comment]
Tried to import a couple of objects with clashing animations: `wpn_bolt_hud.object` and `wpn_vintorez_hud.object`. As a result, I've got e.g. `idle_sprint.001` and `idle_sprint` actions, but, none keyframes were overridden and all animations for both models worked fine.

@xDShot Could you please explain a bit further what files did you import (I wonder if they were SKLS files)?

As for the option - it'd always be better to understand your workflow first in order to build a robust solution. Would you mind explain it a bit?

As for directions - you could take a look at `.action.new(` calls in sources ([for example](https://github.com/PavelBlend/blender-xray/search?q=".actions.new")), then you could use `bpy_armature.name` as a prefix of the action name.

**Comment by xDShot** [comment]
Whoops, my bad. Didn't notice it just created another actions with _.001_ appended without wiping previous one... But still it's not convenient.

>As for the option - it'd always be better to understand your workflow first in order to build a robust solution. Would you mind explain it a bit?

Ok, so I downloaded a weapon mod pack to mess around, then created .object and .skls files with [converter from xray_re-tools](https://bitbucket.org/stalker/xray_re-tools/downloads) and imported them each by one into Blender. Turned out the author decided to use same generic animations names for all weapons.

**Comment by igelbox** [comment]
> the author decided to use same generic animations names for all weapons

I guess that's because of either XRay engine itself or a particular game/modification have predefined animation names. For example, the engine always uses an action with name=`idle_sprint` when the player running with a weapon in hands.

As far as I can recall, we export Blender action names as SDK animation names. And, it seems like we have an issue when we cannot export an animation with an appropriate name if this name is i use on some another action (so, we'll always get some *.001* suffix). So, I believe, a fix for this issue will be welcome.

Actually, I prefer doing the custom prefix approach (as described in this issue text), however, also I have one more solution on the top of my head:
Just omit any .001 like suffixes during the export process. But, this won't help with choosing an action to an armature because it's not clear what's the appropriate/compatible armature for a particular action.

@xDShot if you've implemented this "prefix" feature, feel free to open a pull request.

**Comment by xDShot** [comment]
Wiil do as I get a time.
