### ISSUE TITLE
Exporting .OGF fileformat

### ISSUE THREAD

**Issue by AnomalousBread** [PavelBlend/blender-xray#454]
Hi Pavel I am using your addon to edit some BaS weapons and when i try to export .OGF it gives me a error i think is maybe about maximum vertex weights maybe?
I dont know if its a bug from your addon or from Blender.

Windows 10
Blender 3.0.0
Xray Engine Tools 2.10.0

Here is the model

https://drive.google.com/file/d/1Y_kVOf1Ok3oXN36wqUffls3tn4HJaM7p/view?usp=sharing

![error](https://user-images.githubusercontent.com/97764597/149588793-d26d5558-5954-4475-8cb8-39173037e361.jpg)

**Comment by SamArtGit** [comment]
Export .OGF not finished yet.

**Comment by PavelBlend** [comment]
@AnomalousBread hello. I fixed this error. I couldn't download your file. But I was able to reproduce this error myself.

**Comment by AnomalousBread** [comment]
> 

I managed to edit some models and export them without getting the error but it doesn't always work.
Hopefully you can find solution and you can fix it.
![Anomaly-1 5 1 2 Screenshot 2022 01 15 - 18 30 01 83](https://user-images.githubusercontent.com/97764597/149634124-c8e44f63-ee77-4eb5-80bc-7aa2c7f2a9be.png)

On this M4 I managed to remove the ironsights and change the EoTech holographic sight to a different one from a different model (SCAR-H).

**Comment by PavelBlend** [comment]
> but it doesn't always work

what do you mean it doesn't always work? What is the text of the error? I also need a blend file that reproduces the error.

I can't download your blend file in the first post because I don't have access/read rights to it.

You can add zip files right here.

@AnomalousBread I fixed this error in the commit: 0d9c48aa7f11e00f6f28181384f9ddb3fdd3f923

You need to download it from here:
https://github.com/PavelBlend/blender-xray/tree/0d9c48aa7f11e00f6f28181384f9ddb3fdd3f923 (Code > Download ZIP)

If you have other errors, then write.

**Comment by AnomalousBread** [comment]
> 

Here is the link to the model hopefully this one works https://easyupload.io/hr2wnr

Also i found a new error with version 2.11.0
[NewError.txt](https://github.com/PavelBlend/blender-xray/files/7877716/NewError.txt)

**Comment by PavelBlend** [comment]
@AnomalousBread object `wpn_m4_tac_e0t2_hud.ogf 17` has vertices that don't have vertex groups. You need to assign these vertices to the `wpn_body` group.
![01](https://user-images.githubusercontent.com/7983249/149674634-c96e46d7-9464-48f1-833f-5ec80ea26b6d.jpg)

I will later make a readable, understandable warning instead of such an error.
