### ISSUE TITLE
Armature not exported to .object

### ISSUE THREAD

**Issue by MarkedFour9027** [PavelBlend/blender-xray#588]
I'm trying to export Armature and Mesh into .object, but it not exported well. Only Mesh is exported, but armature not

here my .blend
https://drive.google.com/file/d/1iArCdsnUrPT0laOfXBs4V4Byk3UEm99h/view?usp=sharing

Blender i used: 3.1.2
XRay Tools: 2.13.1

Still not exported in XRay Tools 2.18.2

**Comment by PavelBlend** [comment]
@MarkedFour9027 нужно у скелета включить параметр `Object`.
![1](https://user-images.githubusercontent.com/7983249/211200686-8c9b3278-fde5-47ea-8f18-f4412fd907a4.jpg)

Ещё нужно переименовать группу вершин `bullat1` на `bullet1`.

И изменить тип объекта на `Dynamic`, вместо `Static`.
![2](https://user-images.githubusercontent.com/7983249/211200694-fffbc5b9-aea6-4911-a757-595ce5b703c8.jpg)

Ещё скелет имеет больше одной главной кости.
![3](https://user-images.githubusercontent.com/7983249/211200698-46616d53-925f-4599-b99f-cc5d4eef24d1.jpg)

В сталкере скелет должен иметь только одну главную кость.

Главная кость - это кость, которая не имеет родителя и является вершиной иерархии.

Нужно костям `mag`, `mag2`, `bullet1`, `bullet2` установить родителя в виде кости `wpn_body`.
![4](https://user-images.githubusercontent.com/7983249/211200704-84e0d92c-3274-41fc-8c4f-fc0ecc6ceea4.jpg)

# **ENG:**

@MarkedFour9027 you need to enable the `Object` parameter for the skeleton.
![1](https://user-images.githubusercontent.com/7983249/211200686-8c9b3278-fde5-47ea-8f18-f4412fd907a4.jpg)

We also need to rename the vertex group `bullat1` to `bullet1`.

And change the object type to `Dynamic` instead of `Static`.
![2](https://user-images.githubusercontent.com/7983249/211200694-fffbc5b9-aea6-4911-a757-595ce5b703c8.jpg)

The skeleton also has more than one main bone.
![3](https://user-images.githubusercontent.com/7983249/211200698-46616d53-925f-4599-b99f-cc5d4eef24d1.jpg)

In a stalker, a skeleton must have only one main bone.

The main bone is the bone that has no parent and is the top of the hierarchy.

The bones `mag`, `mag2`, `bullet1`, `bullet2` need to be parented as the `wpn_body` bone.
![4](https://user-images.githubusercontent.com/7983249/211200704-84e0d92c-3274-41fc-8c4f-fc0ecc6ceea4.jpg)
