### ISSUE TITLE
Question about your Blender Rig

### ISSUE THREAD

**Issue by tpaulrazvan** [PavelBlend/blender-xray#815]
Pavel-Blend. This might not be the best place to ask you this. 
But will you licence your RIG for FP hands 

https://gamebanana.com/models/4287

Under a CC0 licence to be allowed to use in commercial/non commercial products?

I am talking only about the skeleton/armature. No model. Only the rig. 

Thanks

**Comment by PavelBlend** [comment]
@tpaulrazvan How do I change the license on gamebanana so it only applies to the skeleton and rig? Is this possible to do? Or will I have to create a new blend file and upload it separately?

And now I looked at the skeleton. I see that the names of the bones are not mine, but are taken from the game STALKER. I took the names from the game because I wanted the skeleton to be consistent and similar to other skeletons in the game. Is it possible to install CC0 license in this case?

**Comment by tpaulrazvan** [comment]
Pretty sure a re-upload with a ReadMe.txt that says this is enough (including that the names are based off stalker's ones).

Or an additional upload on Sketchfab.

But the rig itself is from scratch no? I assume names are like STALKER to ease modding the game?

**Comment by PavelBlend** [comment]
> But the rig itself is from scratch no?

The bones and rig were created by me. But I took the names of the bones from the game, since I didn’t want to come up with new names and started using the usual ones. I will rename the bones when I create a new zip archive with a readme.txt file.

**Comment by PavelBlend** [comment]
@tpaulrazvan  I added a new file named `fp_hands_aks74u_blender_3.6.zip`.

**Comment by tpaulrazvan** [comment]
Awesome! That was quite fast and nice of you.

Thank you
